export const weatherImages = {
  'light rain': require('../assets/images/moderaterain.png'),
  'moderate rain': require('../assets/images/moderaterain.png'),
  'overcast clouds': require('../assets/images/cloud.png'),
  'few clouds': require('../assets/images/partlycloudy.png'),
  'scattered clouds': require('../assets/images/partlycloudy.png'),
  'broken clouds': require('../assets/images/partlycloudy.png'),
  'heavy intensity rain': require('../assets/images/heavyrain.png'),
  'very heavy rain': require('../assets/images/heavyrain.png'),
  'extreme rain': require('../assets/images/heavyrain.png'),
  'freezing rain': require('../assets/images/moderaterain.png'),
  'light intensity shower rain': require('../assets/images/heavyrain.png'),
  'shower rain': require('../assets/images/moderaterain.png'),
  'heavy intensity shower rain': require('../assets/images/heavyrain.png'),
  'ragged shower rain': require('../assets/images/heavyrain.png'),
  'clear sky': require('../assets/images/sun.png'),
  mist: require('../assets/images/mist.png'),
  rain: require('../assets/images/moderaterain.png'),
  smoke: require('../assets/icons/wind.png'),
  thunderstorm: require('../assets/images/heavyrain.png'),
  null: require('../assets/images/fullStar.png'),
  other: require('../assets/images/fullStar.png'),
};
